version: '3'

services:
  database:
    image: mariadb:10.6-focal
#    build:
#      context: ./
#      dockerfile: ./mariadb/Dockerfile
    container_name: database-website
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_DATABASE=database-website
    volumes:
      - ./dbdata_home:/home
      - dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - app-network
  
  phpmyadmin:
     image: phpmyadmin/phpmyadmin:latest
     ports:
       - 8000:80
     environment:
       - PMA_ARBITRARY=1
       - PMA_HOST=mariadb
     depends_on:
       - database
     networks:
       - app-network

  phpfpm:
    #image: bitnami/php-fpm:7.4-prod
    build:
      context: ./
      dockerfile: ./php/Dockerfile
    working_dir: /var/www/html
    container_name: phpfpm
    restart: unless-stopped
    volumes: 
      - ./webdata:/var/www/html
    depends_on:
      - database
    networks:
      - app-network

  webserver:
    depends_on:
      - phpfpm
    #image: nginx:1.15.12-alpine
    # image: nginx:alpine
    build:
       context: ./
       dockerfile: ./build/Dockerfile
    container_name: webserver-tajalapak
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./webdata:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - ./ssl:/etc/nginx/ssl
#      - certbot-etc:/etc/letsencrypt
    networks:
      - app-network
volumes:
  dbdata:

networks:
  app-network:
    driver: bridge
